# Generated by Django 4.2 on 2023-04-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='sub_date',
            new_name='start_date',
        ),
    ]
